# Generated by Django 5.1.3 on 2024-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_no", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("created_at", models.CharField(max_length=50)),
            ],
        ),
    ]
